name: build linux (amd64) with non-static libraries
on:
   push
   
jobs:
   build:
      name: build linux amd64 (non-static)
      runs-on: ubuntu-latest
   
      steps:
          - name: Checkout Code
            uses: actions/checkout@v2
          - name: Install GCC
            uses: egor-tensin/setup-gcc@v1
            with:
              version: latest
              platform: x64
              cygwin: 0
              cc: 1
              hardlinks: 0
          - name: Setup Python
            uses: actions/setup-python@v4.7.1
            with:
               python-version: 3.10.13
               architecture: x64
          - name: Get Conan
            uses: turtlebrowser/get-conan@v1.2
            with: 
               version: 2.0.13 
          - name: Execute shell commands
            working-directory: ./build
            run: |
               cd build
               conan install ..
               conan build .. 
