name: build linux (amd64) with non-static libraries
on:
   push
   
jobs:
   build:
      name: build linux amd64 (non-static)
      runs-on: ubuntu-latest
   
      steps:
          - name: Install GCC
            # You may pin to the exact commit or the version.
            # uses: egor-tensin/setup-gcc@eaa888eb19115a521fa72b65cd94fe1f25bbcaac
            uses: egor-tensin/setup-gcc@v1
            with:
              # GCC version to install
              version: latest
              # Target platform
              platform: x64
              # Install Cygwin packages
              cygwin: 0
              cc: 1
              hardlinks: 0
